name: npm

on:
  push:
    branches:
      - npm
  pull_request:
    branches:
      - npm

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install npm7
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
